#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AudioGameplay_FunctionLibrary

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AudioGameplay_FunctionLibrary.AudioGameplay_FunctionLibrary_C
// 0x0000 (0x0028 - 0x0028)
class UAudioGameplay_FunctionLibrary_C final  : public UBlueprintFunctionLibrary
{
public:
	static void GetAudioForDamageEvent(class AActor* Receiver, class AActor* Instigator, class USoundBase* ReceiverSound, class USoundBase* InstigatorSound, class USoundBase* ObserverSound, class UObject* __WorldContext, class USoundBase** AudioAsset, bool CallFunc_IsActorLocal_ReturnValue, bool CallFunc_IsActorLocal_ReturnValue_1);
	static void GetAudioForPlayerEvent(class AActor* Target, class USoundBase* OneP_Sound, class USoundBase* ThreeP_Sound, class UObject* __WorldContext, class USoundBase** AudioAsset, bool CallFunc_IsActorLocal_ReturnValue);
	static bool IsActorLocal(class AActor* Actor, class UObject* __WorldContext, class AActor* FinalActor, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue, class AFortAthenaVehicle* K2Node_DynamicCast_AsFort_Athena_Vehicle, bool K2Node_DynamicCast_bSuccess, class AFortWeapon* K2Node_DynamicCast_AsFort_Weapon, bool K2Node_DynamicCast_bSuccess_1, TScriptInterface<class IFortVehicleInterface> CallFunc_BP_GetAllPassengers_self_CastInput, TArray<class AFortPlayerPawn*>& CallFunc_BP_GetAllPassengers_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, class AFortPlayerPawn* CallFunc_Array_Get_Item, bool CallFunc_IsLocallyViewed_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class AFortPlayerState* K2Node_DynamicCast_AsFort_Player_State, bool K2Node_DynamicCast_bSuccess_2, class APawn* CallFunc_GetPawn_ReturnValue, class AFortPlayerPawn* K2Node_DynamicCast_AsFort_Player_Pawn, bool K2Node_DynamicCast_bSuccess_3, bool CallFunc_IsLocallyViewed_ReturnValue_1);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AudioGameplay_FunctionLibrary_C">();
	}
	static class UAudioGameplay_FunctionLibrary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioGameplay_FunctionLibrary_C>();
	}
};

}

