#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraAnimationTransition

#include "Basic.hpp"

#include "CameraAnimationTransition_classes.hpp"
#include "CameraAnimationTransition_parameters.hpp"


namespace SDK
{

// Function CameraAnimationTransition.CameraAnimationTransition_C.MoveCameraUp
// (BlueprintCallable, BlueprintEvent)

void ACameraAnimationTransition_C::MoveCameraUp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CameraAnimationTransition_C", "MoveCameraUp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CameraAnimationTransition.CameraAnimationTransition_C.MoveCameraDown
// (BlueprintCallable, BlueprintEvent)

void ACameraAnimationTransition_C::MoveCameraDown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CameraAnimationTransition_C", "MoveCameraDown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CameraAnimationTransition.CameraAnimationTransition_C.ExecuteUbergraph_CameraAnimationTransition
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_CanChangeCamera_CanChangeCamera               (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UFortFrontEndContext*             CallFunc_GetContext_ReturnValue                        (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FViewTargetTransitionParams      K2Node_MakeStruct_ViewTargetTransitionParams           (NoDestructor)
// bool                                    CallFunc_CanChangeCamera_CanChangeCamera_1             (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACameraAnimationTransition_C::ExecuteUbergraph_CameraAnimationTransition(int32 EntryPoint, bool CallFunc_CanChangeCamera_CanChangeCamera, class UFortFrontEndContext* CallFunc_GetContext_ReturnValue, const struct FViewTargetTransitionParams& K2Node_MakeStruct_ViewTargetTransitionParams, bool CallFunc_CanChangeCamera_CanChangeCamera_1)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CameraAnimationTransition_C", "ExecuteUbergraph_CameraAnimationTransition");

	Params::CameraAnimationTransition_C_ExecuteUbergraph_CameraAnimationTransition Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.CallFunc_CanChangeCamera_CanChangeCamera = CallFunc_CanChangeCamera_CanChangeCamera;
	Parms.CallFunc_GetContext_ReturnValue = CallFunc_GetContext_ReturnValue;
	Parms.K2Node_MakeStruct_ViewTargetTransitionParams = std::move(K2Node_MakeStruct_ViewTargetTransitionParams);
	Parms.CallFunc_CanChangeCamera_CanChangeCamera_1 = CallFunc_CanChangeCamera_CanChangeCamera_1;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CameraAnimationTransition.CameraAnimationTransition_C.CanChangeCamera
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EFrontEndCamera                         FromCamera                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFrontEndCamera                         ToCamera                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Param_CanChangeCamera                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UFortFrontEndContext*             CallFunc_GetContext_ReturnValue                        (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// EFrontEndCamera                         CallFunc_GetFrontEndCamera_ReturnValue                 (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsValid_ReturnValue                           (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_EqualEqual_ByteByte_ReturnValue               (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_NotEqual_ByteByte_ReturnValue                 (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsValid_ReturnValue_1                         (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_BooleanAND_ReturnValue                        (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_BooleanAND_ReturnValue_1                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_BooleanAND_ReturnValue_2                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACameraAnimationTransition_C::CanChangeCamera(EFrontEndCamera FromCamera, EFrontEndCamera ToCamera, bool* Param_CanChangeCamera, class UFortFrontEndContext* CallFunc_GetContext_ReturnValue, EFrontEndCamera CallFunc_GetFrontEndCamera_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_2)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CameraAnimationTransition_C", "CanChangeCamera");

	Params::CameraAnimationTransition_C_CanChangeCamera Parms{};

	Parms.FromCamera = FromCamera;
	Parms.ToCamera = ToCamera;
	Parms.CallFunc_GetContext_ReturnValue = CallFunc_GetContext_ReturnValue;
	Parms.CallFunc_GetFrontEndCamera_ReturnValue = CallFunc_GetFrontEndCamera_ReturnValue;
	Parms.CallFunc_IsValid_ReturnValue = CallFunc_IsValid_ReturnValue;
	Parms.CallFunc_EqualEqual_ByteByte_ReturnValue = CallFunc_EqualEqual_ByteByte_ReturnValue;
	Parms.CallFunc_NotEqual_ByteByte_ReturnValue = CallFunc_NotEqual_ByteByte_ReturnValue;
	Parms.CallFunc_IsValid_ReturnValue_1 = CallFunc_IsValid_ReturnValue_1;
	Parms.CallFunc_BooleanAND_ReturnValue = CallFunc_BooleanAND_ReturnValue;
	Parms.CallFunc_BooleanAND_ReturnValue_1 = CallFunc_BooleanAND_ReturnValue_1;
	Parms.CallFunc_BooleanAND_ReturnValue_2 = CallFunc_BooleanAND_ReturnValue_2;

	UObject::ProcessEvent(Func, &Parms);

	if (Param_CanChangeCamera != nullptr)
		*Param_CanChangeCamera = Parms.Param_CanChangeCamera;
}

}

