#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseInput_0

#include "Basic.hpp"

#include "VerseInput_0_classes.hpp"
#include "VerseInput_0_parameters.hpp"


namespace SDK
{

// Function VerseInput.VerseReplicatedInputDataComponent.OnInputActionTriggered
// (Final, Native, Private, HasOutParams)
// Parameters:
// struct FInputActionInstance             ActionInstance                                         (ConstParm, Parm, OutParm, ReferenceParm, ContainsInstancedReference, NativeAccessSpecifierPublic)

void UVerseReplicatedInputDataComponent::OnInputActionTriggered(struct FInputActionInstance& ActionInstance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VerseReplicatedInputDataComponent", "OnInputActionTriggered");

	Params::VerseReplicatedInputDataComponent_OnInputActionTriggered Parms{};

	Parms.ActionInstance = std::move(ActionInstance);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function VerseInput.VerseReplicatedInputDataComponent.ServerInputActionTriggered
// (Final, Net, NetReliable, Native, Event, Private, NetServer, HasDefaults, Const)
// Parameters:
// struct FGuid                            Guid                                                   (ConstParm, Parm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector                          InputValue                                             (ConstParm, Parm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVerseReplicatedInputDataComponent::ServerInputActionTriggered(struct FGuid& Guid, struct FVector& InputValue) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VerseReplicatedInputDataComponent", "ServerInputActionTriggered");

	Params::VerseReplicatedInputDataComponent_ServerInputActionTriggered Parms{};

	Parms.Guid = std::move(Guid);
	Parms.InputValue = std::move(InputValue);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

