#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UIKit_Button_TopNavBar

#include "Basic.hpp"

#include "WBP_UIKit_Button_TopNavBar_classes.hpp"
#include "WBP_UIKit_Button_TopNavBar_parameters.hpp"


namespace SDK
{

// Function WBP_UIKit_Button_TopNavBar.WBP_UIKit_Button_TopNavBar_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_Button_TopNavBar_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_TopNavBar_C", "BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Button_TopNavBar.WBP_UIKit_Button_TopNavBar_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_Button_TopNavBar_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_TopNavBar_C", "BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Button_TopNavBar.WBP_UIKit_Button_TopNavBar_C.BP_OnWidgetStyled
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_Button_TopNavBar_C::BP_OnWidgetStyled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_TopNavBar_C", "BP_OnWidgetStyled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Button_TopNavBar.WBP_UIKit_Button_TopNavBar_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_UIKit_Button_TopNavBar_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_TopNavBar_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Button_TopNavBar.WBP_UIKit_Button_TopNavBar_C.ExecuteUbergraph_WBP_UIKit_Button_TopNavBar
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWBP_UIKit_Block_BackgroundTopNavBar_C*K2Node_DynamicCast_AsWBP_UIKit_Block_Background_Top_Nav_Bar(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_DynamicCast_bSuccess                            (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FUIKitBlockTiming                K2Node_MakeStruct_UIKitBlockTiming                     (NoDestructor)
// class UWBP_UIKit_Block_BackgroundTopNavBar_C*K2Node_DynamicCast_AsWBP_UIKit_Block_Background_Top_Nav_Bar_1(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_DynamicCast_bSuccess_1                          (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_Event_IsDesignTime                              (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsMobileGame_ReturnValue                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UCommonInputSubsystem*            CallFunc_GetLocalPlayerSubsystem_ReturnValue           (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// ECommonInputType                        CallFunc_GetCurrentInputType_ReturnValue               (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_EqualEqual_ByteByte_ReturnValue               (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Button_TopNavBar_C::ExecuteUbergraph_WBP_UIKit_Button_TopNavBar(int32 EntryPoint, class UWBP_UIKit_Block_BackgroundTopNavBar_C* K2Node_DynamicCast_AsWBP_UIKit_Block_Background_Top_Nav_Bar, bool K2Node_DynamicCast_bSuccess, const struct FUIKitBlockTiming& K2Node_MakeStruct_UIKitBlockTiming, class UWBP_UIKit_Block_BackgroundTopNavBar_C* K2Node_DynamicCast_AsWBP_UIKit_Block_Background_Top_Nav_Bar_1, bool K2Node_DynamicCast_bSuccess_1, bool K2Node_Event_IsDesignTime, bool CallFunc_IsMobileGame_ReturnValue, class UCommonInputSubsystem* CallFunc_GetLocalPlayerSubsystem_ReturnValue, ECommonInputType CallFunc_GetCurrentInputType_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_TopNavBar_C", "ExecuteUbergraph_WBP_UIKit_Button_TopNavBar");

	Params::WBP_UIKit_Button_TopNavBar_C_ExecuteUbergraph_WBP_UIKit_Button_TopNavBar Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.K2Node_DynamicCast_AsWBP_UIKit_Block_Background_Top_Nav_Bar = K2Node_DynamicCast_AsWBP_UIKit_Block_Background_Top_Nav_Bar;
	Parms.K2Node_DynamicCast_bSuccess = K2Node_DynamicCast_bSuccess;
	Parms.K2Node_MakeStruct_UIKitBlockTiming = std::move(K2Node_MakeStruct_UIKitBlockTiming);
	Parms.K2Node_DynamicCast_AsWBP_UIKit_Block_Background_Top_Nav_Bar_1 = K2Node_DynamicCast_AsWBP_UIKit_Block_Background_Top_Nav_Bar_1;
	Parms.K2Node_DynamicCast_bSuccess_1 = K2Node_DynamicCast_bSuccess_1;
	Parms.K2Node_Event_IsDesignTime = K2Node_Event_IsDesignTime;
	Parms.CallFunc_IsMobileGame_ReturnValue = CallFunc_IsMobileGame_ReturnValue;
	Parms.CallFunc_GetLocalPlayerSubsystem_ReturnValue = CallFunc_GetLocalPlayerSubsystem_ReturnValue;
	Parms.CallFunc_GetCurrentInputType_ReturnValue = CallFunc_GetCurrentInputType_ReturnValue;
	Parms.CallFunc_EqualEqual_ByteByte_ReturnValue = CallFunc_EqualEqual_ByteByte_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Button_TopNavBar.WBP_UIKit_Button_TopNavBar_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Button_TopNavBar_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_TopNavBar_C", "PreConstruct");

	Params::WBP_UIKit_Button_TopNavBar_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Button_TopNavBar.WBP_UIKit_Button_TopNavBar_C.SetBangType
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EFortBangType                           EBangType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsValid_ReturnValue                           (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Button_TopNavBar_C::SetBangType(EFortBangType EBangType, bool CallFunc_IsValid_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_TopNavBar_C", "SetBangType");

	Params::WBP_UIKit_Button_TopNavBar_C_SetBangType Parms{};

	Parms.EBangType = EBangType;
	Parms.CallFunc_IsValid_ReturnValue = CallFunc_IsValid_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Button_TopNavBar.WBP_UIKit_Button_TopNavBar_C.SetData
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIKitSelectableButtonViewModel*  VM_Button                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UFortTabViewModel*                K2Node_DynamicCast_AsFort_Tab_Viewmodel                (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_DynamicCast_bSuccess                            (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Button_TopNavBar_C::SetData(class UUIKitSelectableButtonViewModel* VM_Button, class UFortTabViewModel* K2Node_DynamicCast_AsFort_Tab_Viewmodel, bool K2Node_DynamicCast_bSuccess)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_TopNavBar_C", "SetData");

	Params::WBP_UIKit_Button_TopNavBar_C_SetData Parms{};

	Parms.VM_Button = VM_Button;
	Parms.K2Node_DynamicCast_AsFort_Tab_Viewmodel = K2Node_DynamicCast_AsFort_Tab_Viewmodel;
	Parms.K2Node_DynamicCast_bSuccess = K2Node_DynamicCast_bSuccess;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Button_TopNavBar.WBP_UIKit_Button_TopNavBar_C.SetFontStyle
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Temp_bool_Variable                                     (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Temp_bool_Variable_1                                   (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsMobileGame_ReturnValue                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          K2Node_Select_Default                                  (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FFontOutlineSettings             K2Node_MakeStruct_FontOutlineSettings                  (NoDestructor, HasGetValueTypeHash)
// class UObject*                          K2Node_Select_Default_1                                (ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FSlateFontInfo                   K2Node_MakeStruct_SlateFontInfo                        (HasGetValueTypeHash)

void UWBP_UIKit_Button_TopNavBar_C::SetFontStyle(bool Temp_bool_Variable, bool Temp_bool_Variable_1, bool CallFunc_IsMobileGame_ReturnValue, class UObject* K2Node_Select_Default, const struct FFontOutlineSettings& K2Node_MakeStruct_FontOutlineSettings, class UObject* K2Node_Select_Default_1, const struct FSlateFontInfo& K2Node_MakeStruct_SlateFontInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_TopNavBar_C", "SetFontStyle");

	Params::WBP_UIKit_Button_TopNavBar_C_SetFontStyle Parms{};

	Parms.Temp_bool_Variable = Temp_bool_Variable;
	Parms.Temp_bool_Variable_1 = Temp_bool_Variable_1;
	Parms.CallFunc_IsMobileGame_ReturnValue = CallFunc_IsMobileGame_ReturnValue;
	Parms.K2Node_Select_Default = K2Node_Select_Default;
	Parms.K2Node_MakeStruct_FontOutlineSettings = std::move(K2Node_MakeStruct_FontOutlineSettings);
	Parms.K2Node_Select_Default_1 = K2Node_Select_Default_1;
	Parms.K2Node_MakeStruct_SlateFontInfo = std::move(K2Node_MakeStruct_SlateFontInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Button_TopNavBar.WBP_UIKit_Button_TopNavBar_C.SetFortTabViewModel
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortTabViewModel*                ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UMVVMView*                        CallFunc_GetExtension_ReturnValue                      (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// TScriptInterface<class INotifyFieldValueChanged>CallFunc_SetViewModel_ViewModel_CastInput              (ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
// bool                                    CallFunc_SetViewModel_ReturnValue                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Button_TopNavBar_C::SetFortTabViewModel(class UFortTabViewModel* ViewModel, class UMVVMView* CallFunc_GetExtension_ReturnValue, TScriptInterface<class INotifyFieldValueChanged> CallFunc_SetViewModel_ViewModel_CastInput, bool CallFunc_SetViewModel_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_TopNavBar_C", "SetFortTabViewModel");

	Params::WBP_UIKit_Button_TopNavBar_C_SetFortTabViewModel Parms{};

	Parms.ViewModel = ViewModel;
	Parms.CallFunc_GetExtension_ReturnValue = CallFunc_GetExtension_ReturnValue;
	Parms.CallFunc_SetViewModel_ViewModel_CastInput = CallFunc_SetViewModel_ViewModel_CastInput;
	Parms.CallFunc_SetViewModel_ReturnValue = CallFunc_SetViewModel_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Button_TopNavBar.WBP_UIKit_Button_TopNavBar_C.SetIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Param_Icon                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// EFortUIFeature                          UIFeature                                              (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsMobileGame_ReturnValue                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_EqualEqual_ByteByte_ReturnValue               (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFortUIFeature                          CallFunc_GetLinkedUIFeature_ReturnValue                (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FMargin                          K2Node_MakeStruct_Margin                               (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_IsValid_ReturnValue                           (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_EqualEqual_ByteByte_ReturnValue_1             (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_BooleanOR_ReturnValue                         (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_EqualEqual_ByteByte_ReturnValue_2             (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_BooleanOR_ReturnValue_1                       (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Button_TopNavBar_C::SetIcon(class UObject* Param_Icon, EFortUIFeature UIFeature, bool CallFunc_IsMobileGame_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, EFortUIFeature CallFunc_GetLinkedUIFeature_ReturnValue, const struct FMargin& K2Node_MakeStruct_Margin, bool CallFunc_IsValid_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, bool CallFunc_BooleanOR_ReturnValue_1)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_TopNavBar_C", "SetIcon");

	Params::WBP_UIKit_Button_TopNavBar_C_SetIcon Parms{};

	Parms.Param_Icon = Param_Icon;
	Parms.UIFeature = UIFeature;
	Parms.CallFunc_IsMobileGame_ReturnValue = CallFunc_IsMobileGame_ReturnValue;
	Parms.CallFunc_EqualEqual_ByteByte_ReturnValue = CallFunc_EqualEqual_ByteByte_ReturnValue;
	Parms.CallFunc_GetLinkedUIFeature_ReturnValue = CallFunc_GetLinkedUIFeature_ReturnValue;
	Parms.K2Node_MakeStruct_Margin = std::move(K2Node_MakeStruct_Margin);
	Parms.CallFunc_IsValid_ReturnValue = CallFunc_IsValid_ReturnValue;
	Parms.CallFunc_EqualEqual_ByteByte_ReturnValue_1 = CallFunc_EqualEqual_ByteByte_ReturnValue_1;
	Parms.CallFunc_BooleanOR_ReturnValue = CallFunc_BooleanOR_ReturnValue;
	Parms.CallFunc_EqualEqual_ByteByte_ReturnValue_2 = CallFunc_EqualEqual_ByteByte_ReturnValue_2;
	Parms.CallFunc_BooleanOR_ReturnValue_1 = CallFunc_BooleanOR_ReturnValue_1;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Button_TopNavBar.WBP_UIKit_Button_TopNavBar_C.SetText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Param_Text                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// EFortUIFeature                          UIFeature                                              (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsMobileGame_ReturnValue                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_IsValid_ReturnValue                           (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_EqualEqual_ByteByte_ReturnValue               (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             CallFunc_SelectText_ReturnValue                        ()
// EFortUIFeature                          CallFunc_GetLinkedUIFeature_ReturnValue                (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_EqualEqual_ByteByte_ReturnValue_1             (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_EqualEqual_ByteByte_ReturnValue_2             (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_BooleanOR_ReturnValue                         (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             CallFunc_GetTabDisplayName_ReturnValue                 ()

void UWBP_UIKit_Button_TopNavBar_C::SetText(class FText Param_Text, EFortUIFeature UIFeature, bool CallFunc_IsMobileGame_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, class FText CallFunc_SelectText_ReturnValue, EFortUIFeature CallFunc_GetLinkedUIFeature_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, bool CallFunc_BooleanOR_ReturnValue, class FText CallFunc_GetTabDisplayName_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_TopNavBar_C", "SetText");

	Params::WBP_UIKit_Button_TopNavBar_C_SetText Parms{};

	Parms.Param_Text = Param_Text;
	Parms.UIFeature = UIFeature;
	Parms.CallFunc_IsMobileGame_ReturnValue = CallFunc_IsMobileGame_ReturnValue;
	Parms.CallFunc_IsValid_ReturnValue = CallFunc_IsValid_ReturnValue;
	Parms.CallFunc_EqualEqual_ByteByte_ReturnValue = CallFunc_EqualEqual_ByteByte_ReturnValue;
	Parms.CallFunc_SelectText_ReturnValue = CallFunc_SelectText_ReturnValue;
	Parms.CallFunc_GetLinkedUIFeature_ReturnValue = CallFunc_GetLinkedUIFeature_ReturnValue;
	Parms.CallFunc_EqualEqual_ByteByte_ReturnValue_1 = CallFunc_EqualEqual_ByteByte_ReturnValue_1;
	Parms.CallFunc_EqualEqual_ByteByte_ReturnValue_2 = CallFunc_EqualEqual_ByteByte_ReturnValue_2;
	Parms.CallFunc_BooleanOR_ReturnValue = CallFunc_BooleanOR_ReturnValue;
	Parms.CallFunc_GetTabDisplayName_ReturnValue = CallFunc_GetTabDisplayName_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Button_TopNavBar.WBP_UIKit_Button_TopNavBar_C.SetTextLayout
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FMargin                          K2Node_MakeStruct_Margin                               (ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FVector2D                        CallFunc_MakeVector2D_ReturnValue                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FMargin                          K2Node_MakeStruct_Margin_1                             (ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FVector2D                        CallFunc_MakeVector2D_ReturnValue_1                    (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FMargin                          K2Node_MakeStruct_Margin_2                             (ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    CallFunc_IsMobileGame_ReturnValue                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Button_TopNavBar_C::SetTextLayout(const struct FMargin& K2Node_MakeStruct_Margin, const struct FVector2D& CallFunc_MakeVector2D_ReturnValue, const struct FMargin& K2Node_MakeStruct_Margin_1, const struct FVector2D& CallFunc_MakeVector2D_ReturnValue_1, const struct FMargin& K2Node_MakeStruct_Margin_2, bool CallFunc_IsMobileGame_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Button_TopNavBar_C", "SetTextLayout");

	Params::WBP_UIKit_Button_TopNavBar_C_SetTextLayout Parms{};

	Parms.K2Node_MakeStruct_Margin = std::move(K2Node_MakeStruct_Margin);
	Parms.CallFunc_MakeVector2D_ReturnValue = std::move(CallFunc_MakeVector2D_ReturnValue);
	Parms.K2Node_MakeStruct_Margin_1 = std::move(K2Node_MakeStruct_Margin_1);
	Parms.CallFunc_MakeVector2D_ReturnValue_1 = std::move(CallFunc_MakeVector2D_ReturnValue_1);
	Parms.K2Node_MakeStruct_Margin_2 = std::move(K2Node_MakeStruct_Margin_2);
	Parms.CallFunc_IsMobileGame_ReturnValue = CallFunc_IsMobileGame_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}

}

