#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UIKit_Block_InputField_Background

#include "Basic.hpp"

#include "WBP_UIKit_Block_InputField_Background_classes.hpp"
#include "WBP_UIKit_Block_InputField_Background_parameters.hpp"


namespace SDK
{

// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.ExecuteUbergraph_WBP_UIKit_Block_InputField_Background
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_GetIsSelected_IsSelected                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_GetIsSelectable_IsSelectable                  (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_GetIsSelectable_IsSelectable_1                (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_GetIsSelectable_IsSelectable_2                (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CallFunc_GetIsSelectable_IsSelectable_3                (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_Event_IsDesignTime                              (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Block_InputField_Background_C::ExecuteUbergraph_WBP_UIKit_Block_InputField_Background(int32 EntryPoint, bool CallFunc_GetIsSelected_IsSelected, bool CallFunc_GetIsSelectable_IsSelectable, bool CallFunc_GetIsSelectable_IsSelectable_1, bool CallFunc_GetIsSelectable_IsSelectable_2, bool CallFunc_GetIsSelectable_IsSelectable_3, bool K2Node_Event_IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Block_InputField_Background_C", "ExecuteUbergraph_WBP_UIKit_Block_InputField_Background");

	Params::WBP_UIKit_Block_InputField_Background_C_ExecuteUbergraph_WBP_UIKit_Block_InputField_Background Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.CallFunc_GetIsSelected_IsSelected = CallFunc_GetIsSelected_IsSelected;
	Parms.CallFunc_GetIsSelectable_IsSelectable = CallFunc_GetIsSelectable_IsSelectable;
	Parms.CallFunc_GetIsSelectable_IsSelectable_1 = CallFunc_GetIsSelectable_IsSelectable_1;
	Parms.CallFunc_GetIsSelectable_IsSelectable_2 = CallFunc_GetIsSelectable_IsSelectable_2;
	Parms.CallFunc_GetIsSelectable_IsSelectable_3 = CallFunc_GetIsSelectable_IsSelectable_3;
	Parms.K2Node_Event_IsDesignTime = K2Node_Event_IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.OnInstantTransitionToDisabled
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_Block_InputField_Background_C::OnInstantTransitionToDisabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Block_InputField_Background_C", "OnInstantTransitionToDisabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.OnInstantTransitionToEnabled
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_Block_InputField_Background_C::OnInstantTransitionToEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Block_InputField_Background_C", "OnInstantTransitionToEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.OnTransitionDeselectedFocusedRequested
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_Block_InputField_Background_C::OnTransitionDeselectedFocusedRequested()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Block_InputField_Background_C", "OnTransitionDeselectedFocusedRequested");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.OnTransitionDeselectedIdleRequested
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_Block_InputField_Background_C::OnTransitionDeselectedIdleRequested()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Block_InputField_Background_C", "OnTransitionDeselectedIdleRequested");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.OnTransitionDisabledRequested
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_Block_InputField_Background_C::OnTransitionDisabledRequested()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Block_InputField_Background_C", "OnTransitionDisabledRequested");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.OnTransitionEnabledRequested
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_Block_InputField_Background_C::OnTransitionEnabledRequested()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Block_InputField_Background_C", "OnTransitionEnabledRequested");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.OnTransitionFocusedRequested
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_Block_InputField_Background_C::OnTransitionFocusedRequested()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Block_InputField_Background_C", "OnTransitionFocusedRequested");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.OnTransitionPressedRequested
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_Block_InputField_Background_C::OnTransitionPressedRequested()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Block_InputField_Background_C", "OnTransitionPressedRequested");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.OnTransitionReleasedRequested
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_Block_InputField_Background_C::OnTransitionReleasedRequested()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Block_InputField_Background_C", "OnTransitionReleasedRequested");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.OnTransitionSelectedRequested
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_Block_InputField_Background_C::OnTransitionSelectedRequested()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Block_InputField_Background_C", "OnTransitionSelectedRequested");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.OnTransitionUnfocusedRequested
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_Block_InputField_Background_C::OnTransitionUnfocusedRequested()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Block_InputField_Background_C", "OnTransitionUnfocusedRequested");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Block_InputField_Background_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Block_InputField_Background_C", "PreConstruct");

	Params::WBP_UIKit_Block_InputField_Background_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.SetBackgroundBrush
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSlateBrush                      InBrush                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UMaterialInstanceDynamic*         CallFunc_GetDynamicMaterial_ReturnValue                (ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Block_InputField_Background_C::SetBackgroundBrush(struct FSlateBrush& InBrush, class UMaterialInstanceDynamic* CallFunc_GetDynamicMaterial_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Block_InputField_Background_C", "SetBackgroundBrush");

	Params::WBP_UIKit_Block_InputField_Background_C_SetBackgroundBrush Parms{};

	Parms.InBrush = std::move(InBrush);
	Parms.CallFunc_GetDynamicMaterial_ReturnValue = CallFunc_GetDynamicMaterial_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.SetBackgroundMaterial
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInstance*                Material_Instance                                      (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)
// class UMaterialInstanceDynamic*         CallFunc_GetDynamicMaterial_ReturnValue                (ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Block_InputField_Background_C::SetBackgroundMaterial(class UMaterialInstance*& Material_Instance, class UMaterialInstanceDynamic* CallFunc_GetDynamicMaterial_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Block_InputField_Background_C", "SetBackgroundMaterial");

	Params::WBP_UIKit_Block_InputField_Background_C_SetBackgroundMaterial Parms{};

	Parms.Material_Instance = Material_Instance;
	Parms.CallFunc_GetDynamicMaterial_ReturnValue = CallFunc_GetDynamicMaterial_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Block_InputField_Background.WBP_UIKit_Block_InputField_Background_C.SetCornerRadius
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Radius_in_Pixels                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  TopLeft                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  TopRight                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  BottomRight                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  BottomLeft                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     K2Node_MakeStruct_LinearColor                          (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  CallFunc_Conv_BoolToDouble_ReturnValue                 (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   K2Node_MakeStruct_R_ImplicitCast                       (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   K2Node_MakeStruct_B_ImplicitCast                       (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   K2Node_MakeStruct_A_ImplicitCast                       (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   K2Node_MakeStruct_G_ImplicitCast                       (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   CallFunc_SetScalarParameterValue_Value_ImplicitCast    (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Block_InputField_Background_C::SetCornerRadius(bool Radius_in_Pixels, double TopLeft, double TopRight, double BottomRight, double BottomLeft, const struct FLinearColor& K2Node_MakeStruct_LinearColor, double CallFunc_Conv_BoolToDouble_ReturnValue, float K2Node_MakeStruct_R_ImplicitCast, float K2Node_MakeStruct_B_ImplicitCast, float K2Node_MakeStruct_A_ImplicitCast, float K2Node_MakeStruct_G_ImplicitCast, float CallFunc_SetScalarParameterValue_Value_ImplicitCast)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Block_InputField_Background_C", "SetCornerRadius");

	Params::WBP_UIKit_Block_InputField_Background_C_SetCornerRadius Parms{};

	Parms.Radius_in_Pixels = Radius_in_Pixels;
	Parms.TopLeft = TopLeft;
	Parms.TopRight = TopRight;
	Parms.BottomRight = BottomRight;
	Parms.BottomLeft = BottomLeft;
	Parms.K2Node_MakeStruct_LinearColor = std::move(K2Node_MakeStruct_LinearColor);
	Parms.CallFunc_Conv_BoolToDouble_ReturnValue = CallFunc_Conv_BoolToDouble_ReturnValue;
	Parms.K2Node_MakeStruct_R_ImplicitCast = K2Node_MakeStruct_R_ImplicitCast;
	Parms.K2Node_MakeStruct_B_ImplicitCast = K2Node_MakeStruct_B_ImplicitCast;
	Parms.K2Node_MakeStruct_A_ImplicitCast = K2Node_MakeStruct_A_ImplicitCast;
	Parms.K2Node_MakeStruct_G_ImplicitCast = K2Node_MakeStruct_G_ImplicitCast;
	Parms.CallFunc_SetScalarParameterValue_Value_ImplicitCast = CallFunc_SetScalarParameterValue_Value_ImplicitCast;

	UObject::ProcessEvent(Func, &Parms);
}

}

