#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UIKit_Dialog

#include "Basic.hpp"

#include "WBP_UIKit_Dialog_classes.hpp"
#include "WBP_UIKit_Dialog_parameters.hpp"


namespace SDK
{

// Function WBP_UIKit_Dialog.WBP_UIKit_Dialog_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_Dialog_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Dialog_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Dialog.WBP_UIKit_Dialog_C.BP_OnDeactivated
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_Dialog_C::BP_OnDeactivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Dialog_C", "BP_OnDeactivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Dialog.WBP_UIKit_Dialog_C.ExecuteUbergraph_WBP_UIKit_Dialog
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_Event_IsDesignTime                              (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Dialog_C::ExecuteUbergraph_WBP_UIKit_Dialog(int32 EntryPoint, bool K2Node_Event_IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Dialog_C", "ExecuteUbergraph_WBP_UIKit_Dialog");

	Params::WBP_UIKit_Dialog_C_ExecuteUbergraph_WBP_UIKit_Dialog Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.K2Node_Event_IsDesignTime = K2Node_Event_IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Dialog.WBP_UIKit_Dialog_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Dialog_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Dialog_C", "PreConstruct");

	Params::WBP_UIKit_Dialog_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Dialog.WBP_UIKit_Dialog_C.SetUIKitDialogViewModel
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUIKitDialogViewModel*            ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UMVVMView*                        CallFunc_GetExtension_ReturnValue                      (ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// TScriptInterface<class INotifyFieldValueChanged>CallFunc_SetViewModel_ViewModel_CastInput              (ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
// bool                                    CallFunc_SetViewModel_ReturnValue                      (ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Dialog_C::SetUIKitDialogViewModel(class UUIKitDialogViewModel* ViewModel, class UMVVMView* CallFunc_GetExtension_ReturnValue, TScriptInterface<class INotifyFieldValueChanged> CallFunc_SetViewModel_ViewModel_CastInput, bool CallFunc_SetViewModel_ReturnValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_Dialog_C", "SetUIKitDialogViewModel");

	Params::WBP_UIKit_Dialog_C_SetUIKitDialogViewModel Parms{};

	Parms.ViewModel = ViewModel;
	Parms.CallFunc_GetExtension_ReturnValue = CallFunc_GetExtension_ReturnValue;
	Parms.CallFunc_SetViewModel_ViewModel_CastInput = CallFunc_SetViewModel_ViewModel_CastInput;
	Parms.CallFunc_SetViewModel_ReturnValue = CallFunc_SetViewModel_ReturnValue;

	UObject::ProcessEvent(Func, &Parms);
}

}

